// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: v1/mweets/mweets.proto

package __

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MweetErrorMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MweetErrorMessage) Reset() {
	*x = MweetErrorMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_mweets_mweets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MweetErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MweetErrorMessage) ProtoMessage() {}

func (x *MweetErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mweets_mweets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MweetErrorMessage.ProtoReflect.Descriptor instead.
func (*MweetErrorMessage) Descriptor() ([]byte, []int) {
	return file_v1_mweets_mweets_proto_rawDescGZIP(), []int{0}
}

func (x *MweetErrorMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MweetErrorMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Mweet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      *string `protobuf:"bytes,1,opt,name=ID,proto3,oneof" json:"ID,omitempty"`
	Image   *string `protobuf:"bytes,2,opt,name=Image,proto3,oneof" json:"Image,omitempty"`
	Content *string `protobuf:"bytes,3,opt,name=Content,proto3,oneof" json:"Content,omitempty"`
	UserId  *string `protobuf:"bytes,4,opt,name=UserId,proto3,oneof" json:"UserId,omitempty"`
}

func (x *Mweet) Reset() {
	*x = Mweet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_mweets_mweets_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mweet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mweet) ProtoMessage() {}

func (x *Mweet) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mweets_mweets_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mweet.ProtoReflect.Descriptor instead.
func (*Mweet) Descriptor() ([]byte, []int) {
	return file_v1_mweets_mweets_proto_rawDescGZIP(), []int{1}
}

func (x *Mweet) GetID() string {
	if x != nil && x.ID != nil {
		return *x.ID
	}
	return ""
}

func (x *Mweet) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *Mweet) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *Mweet) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type MweetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mweet *Mweet `protobuf:"bytes,1,opt,name=mweet,proto3" json:"mweet,omitempty"`
}

func (x *MweetResponse) Reset() {
	*x = MweetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_mweets_mweets_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MweetResponse) ProtoMessage() {}

func (x *MweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mweets_mweets_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MweetResponse.ProtoReflect.Descriptor instead.
func (*MweetResponse) Descriptor() ([]byte, []int) {
	return file_v1_mweets_mweets_proto_rawDescGZIP(), []int{2}
}

func (x *MweetResponse) GetMweet() *Mweet {
	if x != nil {
		return x.Mweet
	}
	return nil
}

type ListMweetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListMweetsRequest) Reset() {
	*x = ListMweetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_mweets_mweets_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMweetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMweetsRequest) ProtoMessage() {}

func (x *ListMweetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mweets_mweets_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMweetsRequest.ProtoReflect.Descriptor instead.
func (*ListMweetsRequest) Descriptor() ([]byte, []int) {
	return file_v1_mweets_mweets_proto_rawDescGZIP(), []int{3}
}

type CreateMweetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Image   string `protobuf:"bytes,2,opt,name=Image,proto3" json:"Image,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	UserId  string `protobuf:"bytes,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *CreateMweetRequest) Reset() {
	*x = CreateMweetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_mweets_mweets_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMweetRequest) ProtoMessage() {}

func (x *CreateMweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mweets_mweets_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMweetRequest.ProtoReflect.Descriptor instead.
func (*CreateMweetRequest) Descriptor() ([]byte, []int) {
	return file_v1_mweets_mweets_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMweetRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateMweetRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateMweetRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateMweetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateMweetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      string  `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Content *string `protobuf:"bytes,2,opt,name=Content,proto3,oneof" json:"Content,omitempty"`
	Image   *string `protobuf:"bytes,3,opt,name=Image,proto3,oneof" json:"Image,omitempty"`
	UserId  string  `protobuf:"bytes,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *UpdateMweetRequest) Reset() {
	*x = UpdateMweetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_mweets_mweets_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMweetRequest) ProtoMessage() {}

func (x *UpdateMweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mweets_mweets_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMweetRequest.ProtoReflect.Descriptor instead.
func (*UpdateMweetRequest) Descriptor() ([]byte, []int) {
	return file_v1_mweets_mweets_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMweetRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateMweetRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *UpdateMweetRequest) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *UpdateMweetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteMweetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteMweetRequest) Reset() {
	*x = DeleteMweetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_mweets_mweets_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMweetRequest) ProtoMessage() {}

func (x *DeleteMweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mweets_mweets_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMweetRequest.ProtoReflect.Descriptor instead.
func (*DeleteMweetRequest) Descriptor() ([]byte, []int) {
	return file_v1_mweets_mweets_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteMweetRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteMweetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteMweetResponse) Reset() {
	*x = DeleteMweetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_mweets_mweets_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMweetResponse) ProtoMessage() {}

func (x *DeleteMweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_mweets_mweets_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMweetResponse.ProtoReflect.Descriptor instead.
func (*DeleteMweetResponse) Descriptor() ([]byte, []int) {
	return file_v1_mweets_mweets_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMweetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_v1_mweets_mweets_proto protoreflect.FileDescriptor

var file_v1_mweets_mweets_proto_rawDesc = []byte{
	0x0a, 0x16, 0x76, 0x31, 0x2f, 0x6d, 0x77, 0x65, 0x65, 0x74, 0x73, 0x2f, 0x6d, 0x77, 0x65, 0x65,
	0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x76, 0x31, 0x2e, 0x6d, 0x77, 0x65,
	0x65, 0x74, 0x73, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x39, 0x0a, 0x11, 0x4d, 0x77, 0x65, 0x65, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x9b, 0x01, 0x0a,
	0x05, 0x4d, 0x77, 0x65, 0x65, 0x74, 0x12, 0x13, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x49, 0x44, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x88,
	0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x49, 0x44, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x0d, 0x4d, 0x77,
	0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x6d,
	0x77, 0x65, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x31, 0x2e,
	0x6d, 0x77, 0x65, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x77, 0x65, 0x65, 0x74, 0x52, 0x05, 0x6d, 0x77,
	0x65, 0x65, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x77, 0x65, 0x65, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6c, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4d, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14,
	0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x8c, 0x01, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1d, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d,
	0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x2f, 0x0a, 0x13, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x89, 0x03, 0x0a,
	0x06, 0x6d, 0x77, 0x65, 0x65, 0x74, 0x73, 0x12, 0x5d, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4d, 0x77, 0x65, 0x65, 0x74, 0x12, 0x1d, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x77, 0x65, 0x65,
	0x74, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x77, 0x65, 0x65, 0x74,
	0x73, 0x2e, 0x4d, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x22, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x77, 0x65,
	0x65, 0x74, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x55, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x4d, 0x77, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x77, 0x65,
	0x65, 0x74, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x77, 0x65, 0x65, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x77, 0x65, 0x65, 0x74,
	0x73, 0x2e, 0x4d, 0x77, 0x65, 0x65, 0x74, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x12,
	0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x77, 0x65, 0x65, 0x74, 0x73, 0x30, 0x01, 0x12, 0x62, 0x0a,
	0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x77, 0x65, 0x65, 0x74, 0x12, 0x1d, 0x2e, 0x76,
	0x31, 0x2e, 0x6d, 0x77, 0x65, 0x65, 0x74, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d,
	0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x76, 0x31,
	0x2e, 0x6d, 0x77, 0x65, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x1a, 0x0f, 0x2f,
	0x76, 0x31, 0x2f, 0x6d, 0x77, 0x65, 0x65, 0x74, 0x73, 0x2f, 0x7b, 0x49, 0x44, 0x7d, 0x3a, 0x01,
	0x2a, 0x12, 0x65, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x77, 0x65, 0x65, 0x74,
	0x12, 0x1d, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x77, 0x65, 0x65, 0x74, 0x73, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4d, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x77, 0x65, 0x65, 0x74, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4d, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x2a, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x77, 0x65,
	0x65, 0x74, 0x73, 0x2f, 0x7b, 0x49, 0x44, 0x7d, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_mweets_mweets_proto_rawDescOnce sync.Once
	file_v1_mweets_mweets_proto_rawDescData = file_v1_mweets_mweets_proto_rawDesc
)

func file_v1_mweets_mweets_proto_rawDescGZIP() []byte {
	file_v1_mweets_mweets_proto_rawDescOnce.Do(func() {
		file_v1_mweets_mweets_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_mweets_mweets_proto_rawDescData)
	})
	return file_v1_mweets_mweets_proto_rawDescData
}

var file_v1_mweets_mweets_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_mweets_mweets_proto_goTypes = []interface{}{
	(*MweetErrorMessage)(nil),   // 0: v1.mweets.MweetErrorMessage
	(*Mweet)(nil),               // 1: v1.mweets.Mweet
	(*MweetResponse)(nil),       // 2: v1.mweets.MweetResponse
	(*ListMweetsRequest)(nil),   // 3: v1.mweets.ListMweetsRequest
	(*CreateMweetRequest)(nil),  // 4: v1.mweets.CreateMweetRequest
	(*UpdateMweetRequest)(nil),  // 5: v1.mweets.UpdateMweetRequest
	(*DeleteMweetRequest)(nil),  // 6: v1.mweets.DeleteMweetRequest
	(*DeleteMweetResponse)(nil), // 7: v1.mweets.DeleteMweetResponse
}
var file_v1_mweets_mweets_proto_depIdxs = []int32{
	1, // 0: v1.mweets.MweetResponse.mweet:type_name -> v1.mweets.Mweet
	4, // 1: v1.mweets.mweets.CreateMweet:input_type -> v1.mweets.CreateMweetRequest
	3, // 2: v1.mweets.mweets.GetAllMweeter:input_type -> v1.mweets.ListMweetsRequest
	5, // 3: v1.mweets.mweets.UpdateMweet:input_type -> v1.mweets.UpdateMweetRequest
	6, // 4: v1.mweets.mweets.DeleteMweet:input_type -> v1.mweets.DeleteMweetRequest
	2, // 5: v1.mweets.mweets.CreateMweet:output_type -> v1.mweets.MweetResponse
	1, // 6: v1.mweets.mweets.GetAllMweeter:output_type -> v1.mweets.Mweet
	2, // 7: v1.mweets.mweets.UpdateMweet:output_type -> v1.mweets.MweetResponse
	7, // 8: v1.mweets.mweets.DeleteMweet:output_type -> v1.mweets.DeleteMweetResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_mweets_mweets_proto_init() }
func file_v1_mweets_mweets_proto_init() {
	if File_v1_mweets_mweets_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_mweets_mweets_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MweetErrorMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_mweets_mweets_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mweet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_mweets_mweets_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MweetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_mweets_mweets_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMweetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_mweets_mweets_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMweetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_mweets_mweets_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMweetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_mweets_mweets_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMweetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_mweets_mweets_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMweetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_mweets_mweets_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_v1_mweets_mweets_proto_msgTypes[5].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_mweets_mweets_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_mweets_mweets_proto_goTypes,
		DependencyIndexes: file_v1_mweets_mweets_proto_depIdxs,
		MessageInfos:      file_v1_mweets_mweets_proto_msgTypes,
	}.Build()
	File_v1_mweets_mweets_proto = out.File
	file_v1_mweets_mweets_proto_rawDesc = nil
	file_v1_mweets_mweets_proto_goTypes = nil
	file_v1_mweets_mweets_proto_depIdxs = nil
}
